# Generated by Django 2.2.3 on 2020-03-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200306_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('u', 'unidentified'), ('m', 'male'), ('f', 'female')], default='u', max_length=1),
        ),
    ]
