# Generated by Django 3.0.3 on 2020-03-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200323_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('f', 'female'), ('u', 'unidentified'), ('m', 'male')], default='u', max_length=1),
        ),
    ]
