# Generated by Django 2.2.3 on 2020-03-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200323_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('u', 'unidentified'), ('m', 'male'), ('f', 'female')], default='u', max_length=1),
        ),
    ]
