# Generated by Django 2.2.3 on 2020-03-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200325_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('u', 'unidentified'), ('f', 'female'), ('m', 'male')], default='u', max_length=1),
        ),
    ]
