# Generated by Django 2.2.3 on 2020-05-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200326_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male'), ('u', 'unidentified')], default='u', max_length=1),
        ),
    ]
