# Generated by Django 2.2.7 on 2020-02-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
