# Generated by Django 3.0.3 on 2020-02-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20200205_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('Cn', 'Chinese'), ('Ko', 'Korean'), ('Ja', 'Japanese'), ('En', 'English')], default='En', max_length=2),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_id',
            field=models.IntegerField(default=0),
        ),
    ]
