# Generated by Django 3.0.3 on 2020-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20200212_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('ko', 'Korean'), ('cn', 'Chinese'), ('en', 'English'), ('ja', 'Japanese')], default='En', max_length=2),
        ),
    ]
