# Generated by Django 3.0.3 on 2020-02-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20200212_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('₩', 'KRW'), ('$', 'USD'), ('¥', 'JPY'), ('元', 'RMB')], default='$', max_length=2),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('cn', 'Chinese'), ('en', 'English'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=2),
        ),
    ]
