# Generated by Django 2.2.3 on 2020-02-13 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0006_auto_20200212_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('₩', 'KRW'), ('元', 'RMB'), ('$', 'USD'), ('¥', 'JPY')], default='$', max_length=2),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('ko', 'Korean'), ('zh-cn', 'Chinese'), ('ja', 'Japanese'), ('en', 'English')], default='en', max_length=2),
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('ko', 'Korean'), ('zh-cn', 'Chinese'), ('ja', 'Japanese'), ('en', 'English')], default='en', max_length=2)),
                ('type_id', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.ManyToManyField(blank=True, null=True, to='tours.TourType'),
        ),
    ]
