# Generated by Django 2.2.3 on 2020-02-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20200213_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('¥', 'JPY'), ('₩', 'KRW'), ('$', 'USD'), ('元', 'RMB')], default='$', max_length=2),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('zh-cn', 'Chinese'), ('ko', 'Korean'), ('en', 'English'), ('ja', 'Japanese')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.ManyToManyField(blank=True, to='tours.TourType'),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('zh-cn', 'Chinese'), ('ko', 'Korean'), ('en', 'English'), ('ja', 'Japanese')], default='en', max_length=2),
        ),
    ]
