# Generated by Django 3.0.3 on 2020-02-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_auto_20200213_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('₩', 'KRW'), ('$', 'USD'), ('¥', 'JPY'), ('元', 'RMB')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ko', 'Korean'), ('ja', 'Japanese'), ('zh-cn', 'Chinese')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ko', 'Korean'), ('ja', 'Japanese'), ('zh-cn', 'Chinese')], default='en', max_length=5),
        ),
    ]
