# Generated by Django 2.2.3 on 2020-02-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20200215_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mn', models.CharField(max_length=60)),
                ('name_en', models.CharField(max_length=60)),
                ('day', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.IntegerField(default=0)),
                ('price_per', models.IntegerField(default=0)),
                ('price_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='includes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='notincludes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('₩', 'KRW'), ('$', 'USD'), ('¥', 'JPY')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('ja', 'Japanese'), ('ko', 'Korean'), ('en', 'English')], default='en', max_length=5),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('ja', 'Japanese'), ('ko', 'Korean'), ('en', 'English')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.ManyToManyField(to='tours.Itinerary'),
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.ManyToManyField(to='tours.Price'),
        ),
    ]
