# Generated by Django 3.0.3 on 2020-02-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20200215_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('元', 'RMB'), ('₩', 'KRW'), ('¥', 'JPY'), ('$', 'USD')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-cn', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-cn', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=5),
        ),
    ]
