# Generated by Django 3.0.3 on 2020-02-29 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_auto_20200229_1252'),
        ('tours', '0013_auto_20200220_1425'),
    ]

    operations = [
    ]
