# Generated by Django 3.0.3 on 2020-02-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_merge_20200229_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('¥', 'JPY'), ('₩', 'KRW'), ('$', 'USD')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=5),
        ),
    ]
