# Generated by Django 2.2.3 on 2020-03-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_auto_20200305_2021'),
        ('tours', '0017_auto_20200305_1526'),
    ]

    operations = [
    ]
