# Generated by Django 2.2.3 on 2020-03-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_merge_20200306_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='tourimages/')),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('₩', 'KRW'), ('¥', 'JPY')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('ja', 'Japanese'), ('en', 'English'), ('ko', 'Korean')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('ja', 'Japanese'), ('en', 'English'), ('ko', 'Korean')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ManyToManyField(blank=True, to='tours.TourImage'),
        ),
    ]
