# Generated by Django 2.2.3 on 2020-03-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0023_auto_20200306_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourreview',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tourreview',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='tourreview',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('₩', 'KRW'), ('$', 'USD'), ('¥', 'JPY')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('ja', 'Japanese'), ('en', 'English'), ('ko', 'Korean')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourreview',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('ja', 'Japanese'), ('en', 'English'), ('ko', 'Korean')], default='en', max_length=5),
        ),
    ]
