# Generated by Django 2.2.3 on 2020-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0024_auto_20200306_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('¥', 'JPY'), ('$', 'USD'), ('₩', 'KRW')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=5),
        ),
    ]
