# Generated by Django 2.2.3 on 2020-03-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0025_auto_20200306_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourreview',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('₩', 'KRW'), ('¥', 'JPY')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('ja', 'Japanese'), ('ko', 'Korean'), ('en', 'English')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('ja', 'Japanese'), ('ko', 'Korean'), ('en', 'English')], default='en', max_length=5),
        ),
    ]
