# Generated by Django 2.2.3 on 2020-03-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0026_auto_20200307_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('ko', 'Korean'), ('ja', 'Japanese'), ('en', 'English')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourreview',
            name='review',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('ko', 'Korean'), ('ja', 'Japanese'), ('en', 'English')], default='en', max_length=5),
        ),
    ]
