# Generated by Django 2.2.3 on 2020-03-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0027_auto_20200307_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('₩', 'KRW'), ('$', 'USD'), ('¥', 'JPY')], default='$', max_length=5),
        ),
    ]
