# Generated by Django 2.2.3 on 2020-03-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0031_auto_20200323_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('₩', 'KRW'), ('$', 'USD'), ('¥', 'JPY')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('ko', 'Korean'), ('en', 'English'), ('ja', 'Japanese')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('ko', 'Korean'), ('en', 'English'), ('ja', 'Japanese')], default='en', max_length=5),
        ),
    ]
