# Generated by Django 2.2.3 on 2020-03-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0034_auto_20200323_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('¥', 'JPY'), ('$', 'USD'), ('₩', 'KRW')], default='$', max_length=5),
        ),
    ]
