# Generated by Django 3.0.3 on 2020-03-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0039_auto_20200323_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('¥', 'JPY'), ('₩', 'KRW')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ko', 'Korean'), ('ja', 'Japanese')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourreview',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ko', 'Korean'), ('ja', 'Japanese')], default='en', max_length=5),
        ),
    ]
