# Generated by Django 2.2.3 on 2020-03-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0042_auto_20200325_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='rating',
        ),
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('¥', 'JPY'), ('₩', 'KRW')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=5),
        ),
    ]
