# Generated by Django 2.2.3 on 2020-03-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0044_auto_20200325_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('₩', 'KRW'), ('$', 'USD'), ('¥', 'JPY')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=5),
        ),
    ]
