# Generated by Django 2.2.3 on 2020-05-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0045_auto_20200326_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('₩', 'KRW'), ('¥', 'JPY')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ko', 'Korean'), ('ja', 'Japanese')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ko', 'Korean'), ('ja', 'Japanese')], default='en', max_length=5),
        ),
    ]
